config/routes.rb
ATest::Application.routes.draw do
  
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]

  root :to => "pages#home"

  match '/contact', :to => 'pages#contact', via: 'get'
  match '/about', :to => 'pages#about', via: 'get'
  match '/help', :to => 'pages#help', via: 'get'
  match '/signup', :to => 'users#new', via: 'get'
  match '/signin', :to => 'sessions#new', via: 'get'
  match '/signout', :to => 'sessions#destroy', via: 'delete'

end

app/views/layouts/_footer.html.erb
<footer>
	<nav class="round">
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", '#' %></li>
			<li><a href="http://www.sotophone.com/">News</a></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
	<%= link_to image_tag("logo.png",size: "160x100", :alt => "LOGO", :class => "round"), root_path %>
	<nav class="round">
		<ul>
		<li><%= link_to "Home", root_path %></li>
		<% if signed_in? %>
		<li><%= link_to "Profile", current_user %></li>
		<li><%= link_to "Users", users_path %></li>
		<li><%= link_to "Settings", edit_user_path(current_user) %></li>
		<% end %>
		<% if signed_in? %>
			<li><%= link_to "Sign out", signout_path, :method => :delete %></li>
		<% else %>
			<li><%= link_to "Sign in", signin_path %></li>
		<% end %>
		</ul>
	</nav>
</header>

app/views/layouts/_stylesheets.html.erb
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

  <!--[if lt IE 9]>
	<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
  <!--[if lt IE 8]>
  	<%= stylesheet_link_tag 'blueprint/ie' %>
  <![endif]-->
	<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= csrf_meta_tags %>
  <%= render 'layouts/stylesheets' %>
  <%= javascript_include_tag :defaults %>
</head>
<body>
	<div class="container">
		<%= render 'layouts/header' %>

		<section class="round">
			<% flash.each do |key, value| %>
				<div class="flash <%= key %>"><%= value %></div>
			<% end %>
			<%= yield %>
		</section>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
	</div>
</body>
</html>